Log traceback of raised exceptions in resync methods
port-labs/Port-Ocean pull request #50
Opened 2023-08-03 13:59 UTC by Tankilevitch

# Description

What - Log traceback of raised exceptions in resync methods
Why - Until this fix when error occurred in the resync method it was really hard to understand the cause of the failure as only the error was logged without any information on what caused it 
How - Add `logger.exception` in the `resync_error_handling` method

## Type of change

Please leave one option from the following and delete the rest:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)

2023-08-03 16:59 UTC, yairsimantov20 requested changes

2023-08-03 16:59 UTC, yairsimantov20 commented on port_ocean/core/integrations/mixins/utils.py
> +        logger.exception("Failed to execute resync function")
There might be an error with this

2023-08-06 08:34 UTC, Tankilevitch commented on port_ocean/core/integrations/mixins/utils.py
> +        logger.exception("Failed to execute resync function")
handled it

2023-08-06 09:00 UTC, yairsimantov20 approved these changes
🌊

2023-08-06 11:27 UTC, merged